from __future__ import annotations

import json
from pathlib import Path

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
import base64

from fastapi.responses import JSONResponse

from backend.evidence import get_zone_evidence

# ============================================================
# Paths
# ============================================================

PROJECT_ROOT = Path(__file__).resolve().parents[1]

OUTPUT_DIR = PROJECT_ROOT / "outputs"

GEOJSON_PATH = (
    OUTPUT_DIR / "spectral_change_zones.geojson"
)


# ============================================================
# FastAPI application
# ============================================================

app = FastAPI(
    title="TERRAIN API",
    description=(
        "AI-driven satellite image change "
        "intelligence API"
    ),
    version="1.0.0",
)


# ============================================================
# CORS
# ============================================================

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ============================================================
# Health check
# ============================================================

@app.get("/")
def root():
    return {
        "project": "TERRAIN",
        "status": "online",
        "service": "satellite change intelligence API",
    }


@app.get("/health")
def health():
    return {
        "status": "healthy",
    }


# ============================================================
# Change zones
# ============================================================

@app.get("/api/v1/analysis/zones")
def get_change_zones():
    """
    Return the verified geographic change-zone
    GeoJSON generated by the spectral pipeline.
    """

    if not GEOJSON_PATH.exists():
        raise HTTPException(
            status_code=404,
            detail=(
                "Change-zone GeoJSON not found. "
                "Run the spectral pipeline first."
            ),
        )

    try:
        with open(
            GEOJSON_PATH,
            "r",
            encoding="utf-8",
        ) as file:
            geojson = json.load(file)

    except json.JSONDecodeError as exc:
        raise HTTPException(
            status_code=500,
            detail=(
                "Change-zone GeoJSON is invalid."
            ),
        ) from exc

    return geojson

@app.get("/api/v1/analysis/zones/{region_id}/evidence")
def get_zone_evidence_endpoint(
    region_id: int,
):
    try:
        evidence = get_zone_evidence(
            region_id
        )

        return {
            "region_id": evidence[
                "region_id"
            ],
            "bounds": evidence[
                "bounds"
            ],
            "properties": evidence[
                "properties"
            ],
                "band_profile": evidence[
                "band_profile"
            ],

            "ndvi_profile": evidence[
                "ndvi_profile"
            ],

            "spectral_profile": evidence[
                "spectral_profile"
            ],

            "images": {
                "before": (
                    "data:image/png;base64,"
                    + base64.b64encode(
                        evidence[
                            "before_png"
                        ]
                    ).decode("utf-8")
                ),
                "after": (
                    "data:image/png;base64,"
                    + base64.b64encode(
                        evidence[
                            "after_png"
                        ]
                    ).decode("utf-8")
                ),
                "mask": (
                    "data:image/png;base64,"
                    + base64.b64encode(
                        evidence[
                            "mask_png"
                        ]
                    ).decode("utf-8")
                ),
                "overlay": (
                    "data:image/png;base64,"
                    + base64.b64encode(
                        evidence[
                            "overlay_png"
                        ]
                    ).decode("utf-8")
                ),
            },
        }

    except ValueError as exc:
        raise HTTPException(
            status_code=404,
            detail=str(exc),
        )

    except Exception as exc:
        raise HTTPException(
            status_code=500,
            detail=(
                "Failed to generate zone evidence: "
                f"{exc}"
            ),
        )